export interface PaperFormat {
  id: string;
  name: string;
  description: string;
  pageWidth: number;  // in points (72 per inch)
  pageHeight: number; // in points
  columns: number;
  rows: number;
  labelWidth: number;  // in points
  labelHeight: number; // in points
  marginTop: number;   // in points
  marginLeft: number;  // in points
  horizontalGap: number; // gap between columns in points
  verticalGap: number;   // gap between rows in points
}

// Helper to convert inches to points
const inchesToPoints = (inches: number): number => inches * 72;
// Helper to convert mm to points
const mmToPoints = (mm: number): number => mm * 2.83465;

// Standard page sizes in points
const LETTER_WIDTH = inchesToPoints(8.5);
const LETTER_HEIGHT = inchesToPoints(11);
const A4_WIDTH = mmToPoints(210);
const A4_HEIGHT = mmToPoints(297);

export const paperFormats: PaperFormat[] = [
  // Avery US Letter Templates
  {
    id: 'avery-5160',
    name: 'Avery 5160',
    description: 'Address Labels - 30 per sheet (1" x 2-5/8")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 3,
    rows: 10,
    labelWidth: inchesToPoints(2.625),
    labelHeight: inchesToPoints(1),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.1875),
    horizontalGap: inchesToPoints(0.125),
    verticalGap: 0,
  },
  {
    id: 'avery-5161',
    name: 'Avery 5161',
    description: 'Address Labels - 20 per sheet (1" x 4")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 2,
    rows: 10,
    labelWidth: inchesToPoints(4),
    labelHeight: inchesToPoints(1),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'avery-5162',
    name: 'Avery 5162',
    description: 'Address Labels - 14 per sheet (1-1/3" x 4")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 2,
    rows: 7,
    labelWidth: inchesToPoints(4),
    labelHeight: inchesToPoints(1.333),
    marginTop: inchesToPoints(0.833),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'avery-5163',
    name: 'Avery 5163',
    description: 'Shipping Labels - 10 per sheet (2" x 4")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 2,
    rows: 5,
    labelWidth: inchesToPoints(4),
    labelHeight: inchesToPoints(2),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'avery-5164',
    name: 'Avery 5164',
    description: 'Shipping Labels - 6 per sheet (3-1/3" x 4")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 2,
    rows: 3,
    labelWidth: inchesToPoints(4),
    labelHeight: inchesToPoints(3.333),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'avery-5165',
    name: 'Avery 5165',
    description: 'Full Sheet Labels - 1 per sheet (8.5" x 11")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 1,
    rows: 1,
    labelWidth: inchesToPoints(8.5),
    labelHeight: inchesToPoints(11),
    marginTop: 0,
    marginLeft: 0,
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'avery-5167',
    name: 'Avery 5167',
    description: 'Return Address Labels - 80 per sheet (0.5" x 1.75")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 4,
    rows: 20,
    labelWidth: inchesToPoints(1.75),
    labelHeight: inchesToPoints(0.5),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.3125),
    horizontalGap: inchesToPoints(0.3125),
    verticalGap: 0,
  },
  {
    id: 'avery-5168',
    name: 'Avery 5168',
    description: 'Shipping Labels - 4 per sheet (3.5" x 5")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 2,
    rows: 2,
    labelWidth: inchesToPoints(3.5),
    labelHeight: inchesToPoints(5),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.75),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'avery-5195',
    name: 'Avery 5195',
    description: 'Round Labels - 63 per sheet (0.75" diameter)',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 7,
    rows: 9,
    labelWidth: inchesToPoints(0.75),
    labelHeight: inchesToPoints(0.75),
    marginTop: inchesToPoints(0.79),
    marginLeft: inchesToPoints(0.78),
    horizontalGap: inchesToPoints(0.4),
    verticalGap: inchesToPoints(0.4),
  },
  {
    id: 'avery-5260',
    name: 'Avery 5260',
    description: 'Easy Peel Address Labels - 30 per sheet (1" x 2-5/8")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 3,
    rows: 10,
    labelWidth: inchesToPoints(2.625),
    labelHeight: inchesToPoints(1),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.1875),
    horizontalGap: inchesToPoints(0.125),
    verticalGap: 0,
  },
  {
    id: 'avery-5263',
    name: 'Avery 5263',
    description: 'Shipping Labels - 10 per sheet (2" x 4")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 2,
    rows: 5,
    labelWidth: inchesToPoints(4),
    labelHeight: inchesToPoints(2),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'avery-8160',
    name: 'Avery 8160',
    description: 'Inkjet Address Labels - 30 per sheet (1" x 2-5/8")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 3,
    rows: 10,
    labelWidth: inchesToPoints(2.625),
    labelHeight: inchesToPoints(1),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.1875),
    horizontalGap: inchesToPoints(0.125),
    verticalGap: 0,
  },
  {
    id: 'avery-8163',
    name: 'Avery 8163',
    description: 'Inkjet Shipping Labels - 10 per sheet (2" x 4")',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 2,
    rows: 5,
    labelWidth: inchesToPoints(4),
    labelHeight: inchesToPoints(2),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: 0,
    verticalGap: 0,
  },
  // A4 Avery Templates
  {
    id: 'avery-l7160',
    name: 'Avery L7160',
    description: 'A4 Address Labels - 21 per sheet (63.5mm x 38.1mm)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 3,
    rows: 7,
    labelWidth: mmToPoints(63.5),
    labelHeight: mmToPoints(38.1),
    marginTop: mmToPoints(15.1),
    marginLeft: mmToPoints(7.2),
    horizontalGap: mmToPoints(2.5),
    verticalGap: 0,
  },
  {
    id: 'avery-l7161',
    name: 'Avery L7161',
    description: 'A4 Address Labels - 18 per sheet (63.5mm x 46.6mm)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 3,
    rows: 6,
    labelWidth: mmToPoints(63.5),
    labelHeight: mmToPoints(46.6),
    marginTop: mmToPoints(8.8),
    marginLeft: mmToPoints(7.2),
    horizontalGap: mmToPoints(2.5),
    verticalGap: 0,
  },
  {
    id: 'avery-l7162',
    name: 'Avery L7162',
    description: 'A4 Address Labels - 16 per sheet (99.1mm x 33.9mm)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 2,
    rows: 8,
    labelWidth: mmToPoints(99.1),
    labelHeight: mmToPoints(33.9),
    marginTop: mmToPoints(13),
    marginLeft: mmToPoints(4.7),
    horizontalGap: mmToPoints(2.5),
    verticalGap: 0,
  },
  {
    id: 'avery-l7163',
    name: 'Avery L7163',
    description: 'A4 Address Labels - 14 per sheet (99.1mm x 38.1mm)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 2,
    rows: 7,
    labelWidth: mmToPoints(99.1),
    labelHeight: mmToPoints(38.1),
    marginTop: mmToPoints(15.1),
    marginLeft: mmToPoints(4.7),
    horizontalGap: mmToPoints(2.5),
    verticalGap: 0,
  },
  {
    id: 'avery-l7165',
    name: 'Avery L7165',
    description: 'A4 Parcel Labels - 8 per sheet (99.1mm x 67.7mm)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 2,
    rows: 4,
    labelWidth: mmToPoints(99.1),
    labelHeight: mmToPoints(67.7),
    marginTop: mmToPoints(13.1),
    marginLeft: mmToPoints(4.7),
    horizontalGap: mmToPoints(2.5),
    verticalGap: 0,
  },
  {
    id: 'avery-l7166',
    name: 'Avery L7166',
    description: 'A4 Parcel Labels - 6 per sheet (99.1mm x 93.1mm)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 2,
    rows: 3,
    labelWidth: mmToPoints(99.1),
    labelHeight: mmToPoints(93.1),
    marginTop: mmToPoints(8.5),
    marginLeft: mmToPoints(4.7),
    horizontalGap: mmToPoints(2.5),
    verticalGap: 0,
  },
  {
    id: 'avery-l7167',
    name: 'Avery L7167',
    description: 'A4 Full Sheet Label - 1 per sheet',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 1,
    rows: 1,
    labelWidth: mmToPoints(199.6),
    labelHeight: mmToPoints(289.1),
    marginTop: mmToPoints(3.95),
    marginLeft: mmToPoints(5.2),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'avery-l7173',
    name: 'Avery L7173',
    description: 'A4 Shipping Labels - 10 per sheet (99.1mm x 57mm)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 2,
    rows: 5,
    labelWidth: mmToPoints(99.1),
    labelHeight: mmToPoints(57),
    marginTop: mmToPoints(6),
    marginLeft: mmToPoints(4.7),
    horizontalGap: mmToPoints(2.5),
    verticalGap: 0,
  },
  // Generic grid formats for 8.5x11
  {
    id: 'letter-2x4',
    name: 'Letter 2x4',
    description: '8 labels per sheet - 2 columns, 4 rows (8.5x11)',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 2,
    rows: 4,
    labelWidth: inchesToPoints(4),
    labelHeight: inchesToPoints(2.5),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'letter-2x5',
    name: 'Letter 2x5',
    description: '10 labels per sheet - 2 columns, 5 rows (8.5x11)',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 2,
    rows: 5,
    labelWidth: inchesToPoints(4),
    labelHeight: inchesToPoints(2),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'letter-3x7',
    name: 'Letter 3x7',
    description: '21 labels per sheet - 3 columns, 7 rows (8.5x11)',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 3,
    rows: 7,
    labelWidth: inchesToPoints(2.625),
    labelHeight: inchesToPoints(1.4),
    marginTop: inchesToPoints(0.6),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: inchesToPoints(0.1),
    verticalGap: inchesToPoints(0.1),
  },
  {
    id: 'letter-3x10',
    name: 'Letter 3x10',
    description: '30 labels per sheet - 3 columns, 10 rows (8.5x11)',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 3,
    rows: 10,
    labelWidth: inchesToPoints(2.625),
    labelHeight: inchesToPoints(1),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.1875),
    horizontalGap: inchesToPoints(0.125),
    verticalGap: 0,
  },
  {
    id: 'letter-4x10',
    name: 'Letter 4x10',
    description: '40 labels per sheet - 4 columns, 10 rows (8.5x11)',
    pageWidth: LETTER_WIDTH,
    pageHeight: LETTER_HEIGHT,
    columns: 4,
    rows: 10,
    labelWidth: inchesToPoints(2),
    labelHeight: inchesToPoints(1),
    marginTop: inchesToPoints(0.5),
    marginLeft: inchesToPoints(0.25),
    horizontalGap: 0,
    verticalGap: 0,
  },
  // Generic grid formats for A4
  {
    id: 'a4-2x4',
    name: 'A4 2x4',
    description: '8 labels per sheet - 2 columns, 4 rows (A4)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 2,
    rows: 4,
    labelWidth: mmToPoints(99),
    labelHeight: mmToPoints(67.7),
    marginTop: mmToPoints(13),
    marginLeft: mmToPoints(6),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'a4-2x5',
    name: 'A4 2x5',
    description: '10 labels per sheet - 2 columns, 5 rows (A4)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 2,
    rows: 5,
    labelWidth: mmToPoints(99),
    labelHeight: mmToPoints(54),
    marginTop: mmToPoints(13.5),
    marginLeft: mmToPoints(6),
    horizontalGap: 0,
    verticalGap: 0,
  },
  {
    id: 'a4-3x7',
    name: 'A4 3x7',
    description: '21 labels per sheet - 3 columns, 7 rows (A4)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 3,
    rows: 7,
    labelWidth: mmToPoints(63.5),
    labelHeight: mmToPoints(38.1),
    marginTop: mmToPoints(15.1),
    marginLeft: mmToPoints(7.2),
    horizontalGap: mmToPoints(2.5),
    verticalGap: 0,
  },
  {
    id: 'a4-3x8',
    name: 'A4 3x8',
    description: '24 labels per sheet - 3 columns, 8 rows (A4)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 3,
    rows: 8,
    labelWidth: mmToPoints(63.5),
    labelHeight: mmToPoints(33.9),
    marginTop: mmToPoints(12.4),
    marginLeft: mmToPoints(7.2),
    horizontalGap: mmToPoints(2.5),
    verticalGap: 0,
  },
  {
    id: 'a4-4x11',
    name: 'A4 4x11',
    description: '44 labels per sheet - 4 columns, 11 rows (A4)',
    pageWidth: A4_WIDTH,
    pageHeight: A4_HEIGHT,
    columns: 4,
    rows: 11,
    labelWidth: mmToPoints(48.5),
    labelHeight: mmToPoints(25.4),
    marginTop: mmToPoints(8.8),
    marginLeft: mmToPoints(8),
    horizontalGap: mmToPoints(0),
    verticalGap: 0,
  },
];

export function searchFormats(query: string): PaperFormat[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return paperFormats;
  
  return paperFormats.filter(format => {
    return format.name.toLowerCase().includes(lowerQuery) ||
           format.description.toLowerCase().includes(lowerQuery) ||
           format.id.toLowerCase().includes(lowerQuery);
  });
}

export function getFormatById(id: string): PaperFormat | undefined {
  return paperFormats.find(format => format.id === id);
}
